/**
 * Verify the pitch: that it plays, and that what it says is still true.
 *
 *     node video/verify.mjs
 *
 * Two different failures, and the second is the one nobody notices.
 *
 * **It does not play.** A video can be published, reachable, and `200` while the browser offers a
 * download instead of playing it -- which is what a GitHub release asset does, and what this
 * project's watch links did until they were repointed. Header checks catch the common cause, and
 * `deploy-vercel.yml` asserts them. This asks a browser what actually happened, because a
 * response that satisfies every header can still leave the element with no metadata.
 *
 * **It says something that stopped being true.** A pitch video is a recording of a project at a
 * moment, and every figure in it -- how many checks the worked example reports, how many
 * dimensions, how many repositories -- is a claim about artefacts that keep moving. When one of
 * them moves, nothing breaks, nothing fails, and the video confidently states a number that is
 * now wrong. That is the defect this file exists to catch, and it is why the figures below are
 * checked against the artefact that owns each one rather than against a copy of themselves.
 *
 * The video is deliberately *not* regenerated by this script. Rendering it needs ffmpeg, a
 * synthesiser and several minutes; deciding whether it is still accurate needs none of those.
 */

import { readFileSync } from 'node:fs'
import { chromium } from 'playwright'

const DOCS = 'https://estamora-docs.vercel.app'
const VIDEO = `${DOCS}/assets/estamora-pitch.mp4`
const REPORT =
  'https://raw.githubusercontent.com/Estamora-Soroban-Layers/estamora-conformance-runner/main/examples/testnet-contract/report.json'
const REPOS = 'https://api.github.com/orgs/Estamora-Soroban-Layers/repos?per_page=100'
const README = new URL('./README.md', import.meta.url)

/** The profile repository carries community health files rather than a project. */
const PROFILE_REPOSITORY = '.github'

const failures = []
const fail = (message) => {
  failures.push(message)
  console.log(`FAIL ${message}`)
}

/** What the narration states, and the artefact that decides whether it is still true. */
async function checkFigures() {
  const report = await (await fetch(REPORT)).json()

  const dimensions = Object.keys(report.summary).length
  if (dimensions !== 7) {
    fail(`the video says "seven dimensions"; the committed report summarises ${dimensions}`)
  } else {
    console.log(`ok   the report still summarises seven dimensions`)
  }

  const checks = Object.values(report.summary).reduce((total, entry) => total + (entry.total ?? 0), 0)
  if (checks !== 63) {
    fail(`the video says "sixty-three checks"; the committed report records ${checks}`)
  } else {
    console.log(`ok   the committed report still records 63 checks`)
  }

  // The vocabulary is the schema's: a vector is `passed` or `skipped`. Naming a status the
  // document does not use is how this check first reported 20 undecided out of 20 while the
  // report said 19, which is the check lying rather than the video.
  const vectors = report.results.length
  const undecided = report.results.filter((result) => result.status === 'skipped').length
  if (vectors !== 20 || undecided !== 19) {
    fail(`the video says "nineteen of its twenty" vectors were undecided; the report has ${undecided} of ${vectors}`)
  } else {
    console.log(`ok   the report still shows 19 of 20 vectors undecided, and still 0 failed`)
  }

  const failed = Object.values(report.summary).reduce((total, entry) => total + (entry.failed ?? 0), 0)
  if (failed !== 0) {
    fail(`the video says "zero failed"; the committed report records ${failed} failed check(s)`)
  }

  const repositories = await (await fetch(REPOS)).json()
  const projects = repositories.filter((repository) => repository.name !== PROFILE_REPOSITORY)
  if (projects.length !== 4) {
    fail(`the video says "four repositories"; the organization has ${projects.length} project repositories`)
  } else {
    console.log(`ok   the organization still has four project repositories`)
  }

  return report
}

/** The README states the runtime in its first paragraph, and the deployed file decides it. */
async function checkRuntime() {
  const stated = readFileSync(README, 'utf8').match(/(\d+):(\d{2}), 1920×1080/)
  if (!stated) {
    fail('video/README.md no longer states the runtime as "M:SS, 1920x1080"')
    return
  }
  const expected = Number(stated[1]) * 60 + Number(stated[2])

  const probe = await fetch(VIDEO, { headers: { range: 'bytes=0-1023' } })
  if (!probe.ok && probe.status !== 206) {
    fail(`${VIDEO} does not answer a range request (${probe.status})`)
    return
  }
  const type = probe.headers.get('content-type') ?? '<absent>'
  if (!type.startsWith('video/')) {
    fail(`${VIDEO} is served as "${type}"; a browser will download it rather than play it`)
  } else {
    console.log(`ok   the pitch is served as ${type}, with byte ranges`)
  }

  return expected
}

async function checkPlayback(expectedSeconds) {
  const browser = await chromium.launch()
  const pages = [
    { name: 'documentation site', url: `${DOCS}/` },
    { name: 'application', url: 'https://estamora-app.vercel.app/' },
  ]

  for (const target of pages) {
    const page = await browser.newPage({ viewport: { width: 1280, height: 900 } })
    await page.goto(target.url, { waitUntil: 'domcontentloaded', timeout: 60000 })

    if ((await page.locator('video').count()) === 0) {
      fail(`${target.name} embeds no <video> element`)
      await page.close()
      continue
    }

    // `readyState >= 1` is HAVE_METADATA: the browser fetched enough to know the duration, which
    // is the earliest state that means "this plays" rather than "this was served".
    //
    // The middle argument is `arg`, and passing the options object there instead silently leaves
    // the default 30-second timeout in force. It did, and a slow first load failed as though the
    // player were broken.
    await page.waitForFunction(() => document.querySelector('video')?.readyState >= 1, undefined, {
      timeout: 60000,
    })

    const player = page.locator('video').first()
    const state = await player.evaluate((element) => ({
      readyState: element.readyState,
      duration: element.duration,
      width: element.videoWidth,
      height: element.videoHeight,
      controls: element.controls,
    }))

    if (!state.controls) {
      fail(`${target.name}: the player has no controls, so a reader cannot start it`)
    }
    if (state.width !== 1920 || state.height !== 1080) {
      fail(`${target.name}: the video is ${state.width}x${state.height}, and the README says 1920x1080`)
    }

    // Seeking is the property the byte-range requirement exists for. Starting is not the same
    // thing: a player that can only play from the beginning cannot be scrubbed by a reader who
    // has four minutes of a five-minute video left to watch.
    const seeked = await player.evaluate(async (element) => {
      element.currentTime = Math.min(30, element.duration / 2)
      await new Promise((resolve) => element.addEventListener('seeked', resolve, { once: true }))
      return element.currentTime
    })
    if (!(seeked > 0)) {
      fail(`${target.name}: the player could not seek`)
    }

    if (expectedSeconds !== undefined && Math.round(state.duration) !== expectedSeconds) {
      fail(
        `${target.name}: the video runs ${state.duration.toFixed(2)}s and video/README.md states ` +
          `${Math.floor(expectedSeconds / 60)}:${String(expectedSeconds % 60).padStart(2, '0')}`,
      )
    } else {
      console.log(
        `ok   ${target.name}: readyState=${state.readyState}, ${state.width}x${state.height}, ` +
          `${state.duration.toFixed(2)}s, seeked to ${seeked.toFixed(2)}s`,
      )
    }

    await page.close()
  }

  await browser.close()
}

async function main() {
  console.log('the figures the video states, against the artefacts that own them\n')
  await checkFigures()

  console.log('\nthe published file, and what the README claims about it\n')
  const expected = await checkRuntime()

  console.log('\nwhat a browser does with it\n')
  await checkPlayback(expected)

  console.log('')
  if (failures.length > 0) {
    console.log(`verify: ${failures.length} problem(s). The video needs re-recording, or the claim does.`)
    for (const failure of failures) {
      console.log(`::error::${failure}`)
    }
    process.exit(1)
  }
  console.log('verify: the pitch plays, and every figure it states is still true.')
}

main().catch((problem) => {
  console.error(`verify: the check itself failed: ${problem?.message ?? problem}`)
  process.exit(1)
})
