name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build Documentation Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install MkDocs and Material Theme
        run: |
          pip install mkdocs mkdocs-material

      - name: Build MkDocs Site
        run: |
          mkdocs build --strict
